/*
*	edf_header.h
*
*	definition of EDF header offsets
*/

#ifndef EDF_HEADER_IN
#define EDF_HEADER_IN

//Begin fixed-length header section
#define EDF_FIXED_HEADER_BYTES					256
#define EDF_VERSION_OFFSET						0
#define EDF_VERSION_LENGTH						8
#define EDF_PATIENT_INFO_OFFSET					8
#define EDF_PATIENT_INFO_LENGTH					80
#define EDF_LOCAL_RECORDING_INFO_OFFSET			88
#define EDF_LOCAL_RECORDING_INFO_LENGTH			80
#define EDF_START_DATE_OFFSET					168
#define EDF_START_DATE_LENGTH					8
#define EDF_START_TIME_OFFSET					176
#define EDF_START_TIME_LENGTH					8
#define EDF_HEADER_BYTES_OFFSET					184
#define EDF_HEADER_BYTES_LENGTH					8
#define EDF_RESERVED_FIXED_OFFSET				192
#define EDF_RESERVED_FIXED_LENGTH				44
#define EDF_NUMBER_OF_DATA_RECORDS_OFFSET		236
#define EDF_NUMBER_OF_DATA_RECORDS_LENGTH		8
#define EDF_DATA_RECORD_DURATION_OFFSET			244
#define EDF_DATA_RECORD_DURATION_LENGTH			8
#define EDF_NUMBER_OF_SIGNALS_OFFSET			252 //number of channels in file
#define EDF_NUMBER_OF_SIGNALS_LENGTH			4

//Variable-length header region: 256 bytes per channel (signal) in file
#define EDF_VARIABLE_HEADER_BYTES_PER_SIGNAL	256
#define EDF_LABEL_OFFSET						0 //NOTE: offsets are per signal, and are from the start of the variable length region
#define EDF_LABEL_LENGTH						16
#define EDF_TRANSDUCER_TYPE_OFFSET				16
#define EDF_TRANSDUCER_TYPE_LENGTH				80
#define EDF_PHYSICAL_DIMENSION_OFFSET			96
#define EDF_PHYSICAL_DIMENSION_LENGTH			8
#define EDF_PHYSICAL_MINIMUM_OFFSET				104
#define EDF_PHYSICAL_MINIMUM_LENGTH				8
#define EDF_PHYSICAL_MAXIMUM_OFFSET				112
#define EDF_PHYSICAL_MAXIMUM_LENGTH				8
#define EDF_DIGITAL_MINIMUM_OFFSET				120
#define EDF_DIGITAL_MINIMUM_LENGTH				8
#define EDF_DIGITAL_MAXIMUM_OFFSET				128
#define EDF_DIGITAL_MAXIMUM_LENGTH				8
#define EDF_PREFILTERING_OFFSET					136
#define EDF_PREFILTERING_LENGTH					80
#define EDF_SAMPLES_PER_RECORD_OFFSET			216
#define EDF_SAMPLES_PER_RECORD_LENGTH			8
#define EDF_RESERVED_VARIABLE_OFFSET			224
#define EDF_RESERVED_VARIABLE_LENGTH			32


#endif